### ISSUE TITLE
todo: investigate vortex download button

### ISSUE THREAD

**Issue by pikdum** [pikdum/steam-deck#16]
* [ ] look into if it requires premium or not
* [x] write up some documentation on the files to edit to properly set up the associations

**Comment by SirStig** [comment]
Just for you to know, no the Vortex download button is not a premium requirement. Premium just allows downloads from premium servers and a higher download rate. So you can download mods a shit ton faster.

**Comment by pikdum** [comment]
Right, it shouldn't.
But a few people have reported that the button doesn't work for them here without premium.

**Comment by Jcrm87** [comment]
Hi, I have a premium account on Nexus, I would be happy to test this.

I have actually just installed Vortex using your script, and got Oblivion ready to mod. Unfortunately I have tried to download using Nexus and it won't work (nothing happens, Chrome doesn't seem to be handling the links. I tried the instructions you have, but somehow I don't have a "mimeapps.list". I tried creating one but that didn't work either.

I have very basic Linux knowledge but I would love to get this working! I am trying to download a collection for Oblivion, I'd be happy to report here if the fixes worked. Thanks!

**Comment by pikdum** [comment]
I might've got the path for mimeapps.list wrong. Can you check `~/.config/mimeapps.list`?

**Comment by Jcrm87** [comment]
That did it! mimeapps.list was there, I added the lines and now Vortex is taking the downloads directly from Nexus (reboot wasn't even necessary).

Tomorrow I will try downloading a whole collection (I need to make some space first and I want to oversee the process just in case). By having a premium account on Nexus, the install process for a collection should be quite automatic. I will report afterwards, but looking good!

Thanks for the effort and your quick reply.

**Comment by Jcrm87** [comment]
So I tried installing today the Oblivion Rebirth + collection.

The good news is that Nexus & Vortex worked perfectly thanks to your work! The bad news is that it seems like some mods (maybe because of the different folder structures?) aren't working properly. Actually, it seems like the same issues (Missing textures and so on) that I got when I tried installing Oblivion and the same collection on my PC and replacing the files on the Deck's install of the game.

I might try installing fewer mods, one by one. Other than that, your tool worked perfectly and the Nexus premium did too.

**Comment by SirStig** [comment]
> So I tried installing today the Oblivion Rebirth + collection.
> 
> The good news is that Nexus & Vortex worked perfectly thanks to your work! The bad news is that it seems like some mods (maybe because of the different folder structures?) aren't working properly. Actually, it seems like the same issues (Missing textures and so on) that I got when I tried installing Oblivion and the same collection on my PC and replacing the files on the Deck's install of the game.
> 
> I might try installing fewer mods, one by one. Other than that, your tool worked perfectly and the Nexus premium did too.

Question, 

Did the mod pack work on the PC? If not then it could be vortex itself. I’ve had missing texture issues on both my gaming PC’s and on steam deck before. Mods don’t deploy properly but vortex doesn’t notice. Sometimes purging and redeploying or reinstalling mods fixes the issue.

Oblivion only installs files for mode to the games install directory and works almost exactly like Skyrim. Your issue could very well be this. Just like Skyrim Oblivion works off of a Script extender. You must launch the game by using the OBSElauncher.exe for more to load properly. Otherwise you will have missing textures and alike. I’d recommend changing the name of the oblivion launcher to _xxxxx.exe and changing the OBSElauncher.exe file name to the same name as the original launcher. This allows you to easily launch oblivion in gamesome or in steam on desktop mode by just launching it like normal so you have cloud saves and so on.

I’ll give an example just to be clear. Skyrim Special Edition, runs off of SKSE (Skyrim Script Extender) to load most mods. On steam deck, to launch any .exe you have to add it to steam and run it with proton. However adding the SESKSE.exe to steam removes cloud support and other things and is annoying. However launching the game without that launcher will result in missing textured and all sorts of other issues.

pikdums tools actually had a script that you can run for Skyrim. This script copies the plug-in load order and mod load order to the proper place in the Skyrim folder. It also automatically renamed SELauncher.exe to _SELauncher.exe and renamed the SESKSE.exe to SELauncher.exe. This way when you launch Skyrim off of steam it actually is now launching the Script Extender launcher so the mods load and run properly.

**Comment by Jcrm87** [comment]
> > So I tried installing today the Oblivion Rebirth + collection.
> > The good news is that Nexus & Vortex worked perfectly thanks to your work! The bad news is that it seems like some mods (maybe because of the different folder structures?) aren't working properly. Actually, it seems like the same issues (Missing textures and so on) that I got when I tried installing Oblivion and the same collection on my PC and replacing the files on the Deck's install of the game.
> > I might try installing fewer mods, one by one. Other than that, your tool worked perfectly and the Nexus premium did too.
> 
> Question,
> 
> Did the mod pack work on the PC? If not then it could be vortex itself. I’ve had missing texture issues on both my gaming PC’s and on steam deck before. Mods don’t deploy properly but vortex doesn’t notice. Sometimes purging and redeploying or reinstalling mods fixes the issue.
> 
> Oblivion only installs files for mode to the games install directory and works almost exactly like Skyrim. Your issue could very well be this. Just like Skyrim Oblivion works off of a Script extender. You must launch the game by using the OBSElauncher.exe for more to load properly. Otherwise you will have missing textures and alike. I’d recommend changing the name of the oblivion launcher to _xxxxx.exe and changing the OBSElauncher.exe file name to the same name as the original launcher. This allows you to easily launch oblivion in gamesome or in steam on desktop mode by just launching it like normal so you have cloud saves and so on.
> 
> I’ll give an example just to be clear. Skyrim Special Edition, runs off of SKSE (Skyrim Script Extender) to load most mods. On steam deck, to launch any .exe you have to add it to steam and run it with proton. However adding the SESKSE.exe to steam removes cloud support and other things and is annoying. However launching the game without that launcher will result in missing textured and all sorts of other issues.
> 
> pikdums tools actually had a script that you can run for Skyrim. This script copies the plug-in load order and mod load order to the proper place in the Skyrim folder. It also automatically renamed SELauncher.exe to _SELauncher.exe and renamed the SESKSE.exe to SELauncher.exe. This way when you launch Skyrim off of steam it actually is now launching the Script Extender launcher so the mods load and run properly.

Thanks for the reply! Here's some info from my side:

1. I tried the modpack first on PC and it worked perfectly (that was before I tried just copying the PC files over to the deck).
2. I replaced Oblivion.exe with the OBSE version, but the game launches via OblivionLauncher. I tried launching directly with OBSE but to the same results. I did that on desk mode, but I didn't think about the Proton layer.
3. I will try this approach, I think I didn't try this before.
4. I was wondering what those two shortcuts were for (a version for Skyrim and one for FO4). Could an Oblivion one be the solution? How can I do the first part manually to test it?

**Comment by pikdum** [comment]
Merged a PR that adds Oblivion support.
To take use it, you'll probably need to:
1. make sure your oblivion directory is back to default - original Oblivion.exe, OBSE, etc.
2. run the update shortcut, this will add the Oblivion Post-Deploy shortcut
3. open Vortex, make sure everything looks good, deploy + sort mods, etc.
4. close Vortex, run Oblivion Post-Deploy, switch to game mode, launch Oblivion

**Comment by SirStig** [comment]
Didn't know where to get a hold of you. However, I have finished what I was going to. Needs a little tweaking to insure no failing or anything however here is a working I guess proof of concept of having Vortex launch from the .desktop and run a .sh script with it that creates Symlinks, moves Launchers and renames script extenders and so on, all in one without any need for a deploy script. 

Main thing besides a few more different file checks is I didn't have the exact names of the Fallout files that needed to be moved or anything so currently every game is set to just create a Symlink of loadorder.txt and plugins.txt, but again proof of concept so that can be changed easily.

[Update-games.sh](https://github.com/SirStig/Steam-deck-tests)

**Comment by SirStig** [comment]
> Didn't know where to get a hold of you. However, I have finished what I was going to. Needs a little tweaking to insure no failing or anything however here is a working I guess proof of concept of having Vortex launch from the .desktop and run a .sh script with it that creates Symlinks, moves Launchers and renames script extenders and so on, all in one without any need for a deploy script.
> 
> Main thing besides a few more different file checks is I didn't have the exact names of the Fallout files that needed to be moved or anything so currently every game is set to just create a Symlink of loadorder.txt and plugins.txt, but again proof of concept so that can be changed easily.
> 
> [Update-games.sh](https://github.com/SirStig/Steam-deck-tests)

Oh also included the Fallout NV pre-deploy, had to fix it as it was written incorrectly.

**Comment by pikdum** [comment]
Made a ticket for further discussion, but a few quick comments:

* could probably be simplified even further, since it's basically just doing the same thing 6 times for different games
* vortex.desktop is managed by https://github.com/pikdum/vortex-linux, which makes things a bit trickier
* could see this working as a separate shortcut, as an alternative to the post-deploy scripts
* worth thinking about how people might migrate from the post-deploy method to that method

**Comment by Jcrm87** [comment]
Thank you both for your work on this.

Unfortunately I tried the fixes and couldn't get the game to launch anymore. I don't rule out being my mistake at some step, since I am not really proficient on this level.

I might try starting from scratch if I have time, and I will report if I have any different results.

Good luck with the development!

**Comment by SirStig** [comment]
> Thank you both for your work on this.
> 
> 
> 
> Unfortunately I tried the fixes and couldn't get the game to launch anymore. I don't rule out being my mistake at some step, since I am not really proficient on this level.
> 
> 
> 
> I might try starting from scratch if I have time, and I will report if I have any different results.
> 
> 
> 
> Good luck with the development!

Let me try it out, I have Oblivion downloaded with some mods. Sometimes you have to change the comparability mode to “Proton-GE” in order for mods or things to work. I run Skyrim Special Edition with proton-GE

Let me test out oblivion, and I’ll get back to you

**Comment by SirStig** [comment]
> Thank you both for your work on this.
> 
> 
> 
> Unfortunately I tried the fixes and couldn't get the game to launch anymore. I don't rule out being my mistake at some step, since I am not really proficient on this level.

Okay, I launched vortex, installed about 20 mods as well as OBSE. Ran Oblivion_post_deploy.exe.

Switched to game mode, opened Oblivions properties on steam. Changed Compatibility Profile to Proton-GE 8_3 ran Oblivion, it launched ran a game and the mods were installed and working.

**Comment by jupiterbjy** [comment]
With my non-premium account I can confirm that vortex will throw out 403 despite logged-in and can download on win11 desktop without such issue.

![image](https://github.com/pikdum/steam-deck/assets/26041217/ced2558c-502f-4552-9495-e01a1ab42b60)

From [API document](https://app.swaggerhub.com/apis-docs/NexusMods/nexus-mods_public_api_params_in_form_data/1.0#/Mod%20Files/get_v1_games_game_domain_mods_mod_id_files_id_download_link.json):

> `/v1/games/{game_domain_name}/mods/{mod_id}/files/{id}/download_link.json`
> ...
> NOTE: **_Non-premium members must provide the key and expiry_** from the .nxm link provided by the website. It is recommended for clients to extract them from the nxm link before sending this request. This ensures that all non-premium members must access the website to download through the API.

I do notice that link shown on image is lacking trailing `.json` but I'm suspecting less from that.

Rather, what I'm suspecting is that whatever is handling or building the final URL - it's 
 discarding the very required `Key` and `Expiry` parameter which is a-must for free users.

This could explain why premium users could download just fine, as those accounts do not require any key or expiry params on their requests.

**Comment by pikdum** [comment]
Thanks for the info, helped me track down the issue.

Should be fixed with the latest version - will need to run the update shortcut, which will:
1. update vortex-linux
2. update proton to a newer version, if old
3. rebuild desktop shortcuts

Anybody able to update and let me know if the fix worked?

**Comment by jupiterbjy** [comment]
Whoa, that was quick! With current update seems like Browser side link is not passed to Vortex somehow - no message or notification shows up on vortex client side.

Maybe this has something to do with firefox - lemme install chromium and try again

**Comment by pikdum** [comment]
Awesome, thanks for confirming things work.
The issue turned out to be quoting.

Something like this didn't work:

```
 Vortex.exe -d nxm://skyrimspecialedition/mods/98732/files/419179?key=redacted&expires=redacted&user_id=redacted
 ```
 
 But this works:
 
 ```
 Vortex.exe -d 'nxm://skyrimspecialedition/mods/98732/files/419179?key=redacted&expires=redacted&user_id=redacted'
 ```
 
 Not entirely sure why, though. :)
 
 I'll go ahead and close this since it's fixed.
