### ISSUE TITLE
Vortex 1.8

### ISSUE THREAD

**Issue by pikdum** [pikdum/steam-deck#4]
Will need to figure out a way to support Vortex 1.8, eventually.

Some thoughts:
* can I start Vortex in a game's Proton WINEPREFIX, using Wine 8.4+, referencing .NET and other Vortex dependencies installed elsewhere?
  * if so, then that would remove the need for [skyrim-post-deploy.sh](https://github.com/pikdum/steam-deck/blob/master/vortex/skyrim-post-deploy.sh)
  * and make more games work out of the box, like Fallout 4 and other Bethesda games that expect Vortex to have access to game files in Documents/
* could Vortex be distributed as a Flatpak?

**Comment by sonic2kk** [comment]
Building a version of Proton based on Wine 8.4 or above is likely the first step. Unless Proton 8.0 or Bleeding Edge is patched to include the missing Wine call, Proton-tkg may be needed to accomplish this. However I am not sure what compatibility will be like across distros. For the purposes of this project, it should be fine as the Steam Deck should be compatible.

There may be other issues that arise once a build of Proton with the missing method is implemented. There may be other missing calls, or compatibility may be broken for other reasons.

If Proton 8.0 doesn't work, then a build of Proton-tkg using the latest Bleeding Edge Proton could be checked. This should be available from the wine-tkg-git GitHub Actions. I am not sure how Valve manage their Bleeding Edge but I don't believe it's based on the latest Wine staging. Still, there's a chance things like this may be patched in for their Bleeding Edge build.

If no pre-existing builds of Proton have the required patch (or patches), a manual build of Proton based on Wine 8.4 or above may be needed. The tkg build script should allow for this.

<hr>

Once a version of Proton is found that can run Vortex, compatibility will need to be tested. Hopefully there are no breakages. If the issue ends up solely being that a newer Wine version is required, then STL can be updated to use a newer Wine build at least temporarily. If a custom Tkg build is required then I can find a way to host this and have STL download it. This was done previously a long time ago when a custom Wine build was needed for MO2.

However, if compatibility with Vortex is broken, that will also need to be investigated. I don't use Vortex, so I may be limited in what I can do to investigate and fix any compatibility issues if any are on the STL side.

I'm happy to do what I can to help out and submit fixes for STL. Of course, anyone else is free to contribute as well, something I'm trying to improve at is giving others the opportunity to collaborate when they have a desire to.

I would humbly ask that, where possible, we can implement improvements to STL upstream. In other words, getting fixes into STL upstream instead of having them specific to this project :-) 

Thanks!

**Comment by sonic2kk** [comment]
> and make more games work out of the box, like Fallout 4 and other Bethesda games that expect Vortex to have access to game files in Documents/

May be possible to force Vortex and those games to symlink to the Documents folder. This can be done with winecfg, likely can be done with some Winecfg/Winetricks commands as well. Though this may impact game saves.

> Vortex Flatpak 

From what I have seen, and take it with a grain of salt, but distributing Wine applications as Flatpak appears to be a headache. I'm also not sure it would really solve anything, as if Vortex updates, the Flatpak would need to be updated and tested anyway. Controlling how Vortex updates with a custom build may be problematic. Not to mention the maintenance costs, it would essentially be maintaining a separate build of Vortex.

**Comment by sonic2kk** [comment]
Quick follow up for consistency with sonic2kk/steamtinkerlaunch#792: The issue is indeed an incompatibility with Wine. A build of Proton-tkg based on Wine 8.6 worked with at least booting up Vortex.

**Comment by sonic2kk** [comment]
Vortex 1.8.1 Beta now works with GE-Proton8-2. The breakage with `DiscardVirtualMemory` is a result of Chromium requiring this stub in Wine. See this Wine-GE patch (which was also included in GE-Proton8-2): https://github.com/Frogging-Family/wine-tkg-git/issues/1000

This issue can probably be closed as the latest GE-Proton will fix it. The upgrade path is much more straightforward than downloading a nightly Proton-tkg build.

**Comment by sonic2kk** [comment]
The note on the readme is not correct anymore as Vortex 1.8 does work with GE-Proton8-2 as noted above.

**Comment by pikdum** [comment]
Fixed. More details here: https://github.com/sonic2kk/steamtinkerlaunch/issues/806
