### ISSUE TITLE
Vortex cannot find some real files in its explorer

### ISSUE THREAD

**Issue by TigerBeanst** [pikdum/steam-deck#51]
I can find `modsettings.lsx` in `/home/deck/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3/PlayerProfiles/Public/`

![Screenshot_20230929_034423](https://github.com/pikdum/steam-deck/assets/3889846/50f5014f-d2c3-42e7-a12d-48483ef86460)

But in Vortex, using its explorer, I cannot find it, the Public folder is empty.

![Screenshot_20230929_034746](https://github.com/pikdum/steam-deck/assets/3889846/670d3e95-44e0-4531-a1ea-0d64248c30ea)

This seems to directly result in me being unable to deploy mods properly.

![Screenshot_20230929_035045](https://github.com/pikdum/steam-deck/assets/3889846/e708da36-6a56-4aa0-afb5-ffe29b6c275f)

**Comment by pikdum** [comment]
Simplified, everything under Proton has a separate 'Windows install'.

So what you're seeing in Vortex is under ~/.vortex-linux/compatdata/pfx/drive_c/ rather than ~/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/.

So if Vortex needs some files, some solutions:
* manually copy things between the two places as-needed
  * this is what the Skyrim Post-Deploy script does, for example, with loadorder.txt and plugins.txt
* set up a symlink so the files you need are in both places
